"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Paperclip, Send } from "lucide-react";
import { toast } from "sonner";
import { useParams } from "next/navigation";
import { useUserSession } from "@/context/UserContext";

export default function FacultyDoubtDetailPage() {
  const { id } = useParams() as { id: string }; const { isFaculty, isAdmin } = useUserSession(); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const response = await fetch(`/api/doubts/${id}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); };
  useEffect(() => { load().catch((error) => toast.error(error.message)); }, [id]);
  const reply = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const response = await fetch(`/api/doubts/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage(""); setData((current: any) => ({ ...current, doubt: result.doubt })); } catch (error: any) { toast.error(error.message); } finally { setBusy(false); } };
  const resolve = async () => { if (!window.confirm("Resolve this doubt? The student will no longer be able to reply.")) return; const response = await fetch(`/api/doubts/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "resolve" }) }); const result = await response.json(); if (!response.ok) toast.error(result.error); else setData((current: any) => ({ ...current, doubt: result.doubt })); };
  if (!isFaculty && !isAdmin) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-sm text-rose-800">Faculty access is required.</div>;
  if (!data) return <div className="py-16 text-center text-sm text-slate-500">Loading conversation…</div>;
  const { doubt, subject, student } = data;
  return <div className="mx-auto max-w-4xl space-y-5"><Link href="/faculty/doubts" className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft className="h-4 w-4" /> Back to doubts</Link><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-amber-600">{subject?.code} · {subject?.name}</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{doubt.title}</h1><p className="mt-2 text-sm text-slate-500">Student: <strong>{student?.name}</strong> {student?.rollNumber ? `· ${student.rollNumber}` : ""}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{doubt.status.replace("_", " ")}</span></div></header><section className="space-y-3">{doubt.messages.map((item: any, index: number) => <article key={`${item.createdAt}-${index}`} className={`max-w-[90%] rounded-2xl border p-4 ${item.senderRole === "faculty" ? "ml-auto border-amber-100 bg-amber-50" : "border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-3 text-xs"><strong className="text-slate-800">{item.senderRole === "faculty" ? "You" : student?.name || "Student"}</strong><time className="text-slate-400">{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.message}</p>{item.attachments?.map((attachment: any) => <a key={attachment.name} href={attachment.url} download={attachment.name} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-700"><Paperclip className="h-3.5 w-3.5" />{attachment.name}</a>)}</article>)}</section>{doubt.status === "RESOLVED" ? <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-5 w-5" /> Resolved {doubt.resolvedAt ? new Date(doubt.resolvedAt).toLocaleString() : ""}</div> : <><form onSubmit={reply} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><textarea required value={message} onChange={(event) => setMessage(event.target.value)} rows={4} placeholder="Write an academic response…" className="w-full resize-none text-sm text-slate-800 outline-none" /><div className="flex justify-end border-t border-slate-100 pt-3"><button type="submit" disabled={busy || !message.trim()} className="inline-flex items-center gap-2 rounded-lg bg-amber-500 px-4 py-2 text-xs font-semibold text-slate-950 disabled:opacity-50"><Send className="h-4 w-4" />{busy ? "Sending…" : "Send response"}</button></div></form><button type="button" onClick={resolve} className="inline-flex items-center gap-2 rounded-lg border border-emerald-300 px-4 py-2 text-xs font-semibold text-emerald-800 hover:bg-emerald-50"><CheckCircle2 className="h-4 w-4" /> Mark as resolved</button></>}</div>;
}
