"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2, MessageCircleQuestion, Search } from "lucide-react";
import { toast } from "sonner";
import { useUserSession } from "@/context/UserContext";

export default function FacultyDoubtsPage() {
  const { isFaculty, isAdmin } = useUserSession();
  const [doubts, setDoubts] = useState<any[]>([]); const [status, setStatus] = useState("ALL"); const [search, setSearch] = useState("");
  useEffect(() => { fetch("/api/doubts").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setDoubts(data.doubts || []); }).catch((error) => toast.error(error.message)); }, []);
  const filtered = useMemo(() => doubts.filter((doubt) => (status === "ALL" || doubt.status === status) && (!search.trim() || `${doubt.title} ${doubt.student?.name} ${doubt.subject?.name}`.toLowerCase().includes(search.toLowerCase()))), [doubts, status, search]);
  if (!isFaculty && !isAdmin) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-sm text-rose-800">Faculty access is required.</div>;
  const open = doubts.filter((doubt) => doubt.status === "OPEN").length; const progress = doubts.filter((doubt) => doubt.status === "IN_PROGRESS").length; const resolved = doubts.filter((doubt) => doubt.status === "RESOLVED").length;
  return <div className="mx-auto max-w-6xl space-y-6"><header><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-amber-600"><MessageCircleQuestion className="h-4 w-4" /> Faculty workspace</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Student doubts</h1><p className="mt-1 text-sm text-slate-500">Respond to questions from students assigned to your subjects.</p></header><section className="grid grid-cols-3 gap-3"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs text-amber-800">Open</p><p className="mt-1 text-2xl font-bold text-amber-950">{open}</p></div><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4"><p className="text-xs text-indigo-800">In progress</p><p className="mt-1 text-2xl font-bold text-indigo-950">{progress}</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs text-emerald-800">Resolved</p><p className="mt-1 text-2xl font-bold text-emerald-950">{resolved}</p></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search student, subject, or doubt" className="w-full rounded-lg border border-slate-300 py-2.5 pl-9 pr-3 text-sm text-slate-800" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-800"><option value="ALL">All statuses</option><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select></div><div className="mt-5 divide-y divide-slate-100">{filtered.map((doubt) => <Link key={doubt.id} href={`/faculty/doubts/${doubt.id}`} className="flex flex-col gap-3 py-4 transition-colors hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-slate-900">{doubt.student?.name || "Student"}</span><span className="text-xs text-slate-500">{doubt.subject?.code}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${doubt.status === "RESOLVED" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{doubt.status.replace("_", " ")}</span></div><p className="mt-1 text-sm text-slate-700">{doubt.title}</p><p className="mt-1 text-xs text-slate-400">Updated {new Date(doubt.updatedAt).toLocaleString()}</p></div><ArrowUpRight className="h-4 w-4 shrink-0 text-slate-400" /></Link>)}{filtered.length === 0 && <p className="py-12 text-center text-sm text-slate-500">No doubts match these filters.</p>}</div></section></div>;
}
