"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Paperclip, Send, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { useParams } from "next/navigation";
import { useUserSession } from "@/context/UserContext";

export default function DoubtDetailPage() {
  const { id } = useParams() as { id: string };
  const { isStudent } = useUserSession();
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false);
  const load = async () => { const response = await fetch(`/api/doubts/${id}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); };
  useEffect(() => { load().catch((error) => toast.error(error.message)); }, [id]);
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!message.trim()) return; setSending(true); try { const response = await fetch(`/api/doubts/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage(""); setData((current: any) => ({ ...current, doubt: result.doubt })); } catch (error: any) { toast.error(error.message); } finally { setSending(false); } };
  const reopen = async () => { const response = await fetch(`/api/doubts/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "reopen" }) }); const result = await response.json(); if (!response.ok) toast.error(result.error); else setData((current: any) => ({ ...current, doubt: result.doubt })); };
  if (!isStudent) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-sm text-rose-800">Student access is required.</div>;
  if (!data) return <div className="py-16 text-center text-sm text-slate-500">Loading conversation…</div>;
  const { doubt, subject, faculty } = data;
  return <div className="mx-auto max-w-3xl space-y-5"><Link href="/doubts" className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft className="h-4 w-4" /> Back to doubts</Link><header className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">{subject?.code} · {subject?.name}</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{doubt.title}</h1></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${doubt.status === "RESOLVED" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{doubt.status.replace("_", " ")}</span></div><p className="mt-3 text-xs text-slate-500">Faculty: <strong>{faculty?.name}</strong></p></header><section className="space-y-3">{doubt.messages.map((item: any, index: number) => <article key={`${item.createdAt}-${index}`} className={`max-w-[90%] rounded-2xl border p-4 ${item.senderRole === "student" ? "ml-auto border-indigo-100 bg-indigo-50" : "border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-3 text-xs"><strong className="text-slate-800">{item.senderRole === "student" ? "You" : faculty?.name || "Faculty"}</strong><time className="text-slate-400">{new Date(item.createdAt).toLocaleString()}</time></div>{item.message && <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.message}</p>}{item.attachments?.map((attachment: any) => <a key={attachment.name} href={attachment.url} download={attachment.name} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-700"><Paperclip className="h-3.5 w-3.5" />{attachment.name}</a>)}</article>)}</section>{doubt.status === "RESOLVED" ? <div className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="flex items-center gap-2 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-5 w-5" /> This doubt was resolved by faculty.</p><button type="button" onClick={reopen} className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-800"><RotateCcw className="h-4 w-4" /> Reopen</button></div> : <form onSubmit={send} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><textarea value={message} onChange={(event) => setMessage(event.target.value)} rows={4} placeholder="Write a reply…" className="w-full resize-none text-sm text-slate-800 outline-none" /><div className="flex justify-end border-t border-slate-100 pt-3"><button type="submit" disabled={sending || !message.trim()} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50"><Send className="h-4 w-4" />{sending ? "Sending…" : "Send reply"}</button></div></form>}</div>;
}
